// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiRole } from "./AiRole";

export type AiMessage = { role: AiRole, text: string, };
