// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyResult } from "./ApplyResult";
import type { Command } from "./Command";

/**
 * A change the copilot wants to make. Nothing is committed until the user
 * accepts it with `ai_resolve`.
 */
export type AiProposal = { id: string, 
/**
 * Always a `Command::Batch`.
 */
command: Command, 
/**
 * Dry run against the revision the proposal was made on.
 */
preview: ApplyResult, base_revision: number, };
