// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirconRole } from "./AirconRole";

/**
 * Line set sizes and installation limits of an aircon unit, from PH
 * manufacturer manuals (Koppel, Carrier, Daikin). Review defaults only: the
 * unit's own manual and the PME decide.
 */
export type AirconSpec = { role: AirconRole, 
/**
 * Nominal capacity in horsepower, as sold in PH.
 */
hp: number, 
/**
 * Liquid and gas line outside diameters in mm. 0 for window units.
 */
liquid_mm: number, gas_mm: number, 
/**
 * Line set length limits in m, and the largest height difference.
 */
min_line_m: number, max_line_m: number, max_rise_m: number, 
/**
 * Line set length included in a standard PH installation, in m.
 * Installers usually bill each meter beyond it.
 */
included_line_m: number, };
