// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiMessage } from "./AiMessage";
import type { EditScope } from "./EditScope";

export type AiRequest = { message: string, selection_ids: Array<string>, 
/**
 * Level the user is working on. New elements go here. None means the first level.
 */
active_level_id: string | null, 
/**
 * Prior turns of this conversation, oldest first.
 */
history: Array<AiMessage>, 
/**
 * Limits every edit of this turn to the selection (DECISIONS D30). None:
 * the copilot may edit anything the user asks for.
 */
scope: EditScope | null, };
