// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyResult } from "./ApplyResult";

export type AiResolveResult = { 
/**
 * Present when the proposal was accepted and applied.
 */
applied: ApplyResult | null, };
