// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiSettings = { 
/**
 * The key itself never crosses IPC toward the frontend.
 */
has_api_key: boolean, model: string, };
