// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProposal } from "./AiProposal";

export type AiTurn = { reply: string, proposal: AiProposal | null, 
/**
 * Names of the tools the model called, for transparency.
 */
tools_used: Array<string>, };
