// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

export type Annotation = { id: string, level_id: string, 
/**
 * Left end of the first line's baseline. Further lines stack below.
 */
position: Point, text: string, 
/**
 * Text height in model mm at the project scale.
 */
size_mm: number, rotation_deg: number, };
