// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { LiveStatus } from "./LiveStatus";
import type { Presence } from "./Presence";
import type { WindowRequest } from "./WindowRequest";

/**
 * Pushed to the window: the Tauri event `app_event` in the desktop app,
 * `GET /events` (server-sent events) on the dev bridge. Document changes keep
 * their own `doc_changed` event.
 */
export type AppEvent = { "type": "live", status: LiveStatus, } | { "type": "presence", participant_id: string, presence: Presence | null, } | { "type": "chat", message: ChatMessage, } | { "type": "window_request", request: WindowRequest, };
