// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diff } from "./Diff";
import type { DocState } from "./DocState";

/**
 * Result of `apply` and of `preview`. For a preview, `state` is hypothetical
 * and nothing was committed.
 */
export type ApplyResult = { state: DocState, diff: Diff, };
