// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetCategory } from "./AssetCategory";
import type { Point } from "./Point";

/**
 * A placed library object. `catalog_key` refers to `CatalogItem::key`.
 * Local axes before rotation: width along x, depth along y, and +y is the
 * BACK of the object (bed head, sofa back, WC tank, counter splashback).
 */
export type Asset = { id: string, level_id: string, catalog_key: string, name: string, category: AssetCategory, 
/**
 * Center of the footprint.
 */
position: Point, rotation_deg: number, width_mm: number, depth_mm: number, height_mm: number, 
/**
 * Height of the underside above the level floor.
 */
elevation_mm: number, };
