// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Light from a fixture.
 */
export type AssetLight = { 
/**
 * Luminous flux. A 9 W LED bulb sold in PH is about 900 lm.
 */
lumens: number, 
/**
 * Color temperature: 2700 to 3000 warm white, 4000 neutral, 6500 daylight.
 */
kelvin: number, 
/**
 * Switched on in the model. Night views light fixtures that are on.
 */
on: boolean, };
