// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CameraPreset = "eye_level" | "exterior_corner" | "top" | "axonometric" | "room_interior" | "custom";
