// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraPreset } from "./CameraPreset";
import type { Vec3 } from "./Vec3";

export type Camera = { id: string, name: string, preset: CameraPreset, position: Vec3, target: Vec3, fov_deg: number, };
