// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraPreset } from "./CameraPreset";
import type { Vec3 } from "./Vec3";
import type { ViewLight } from "./ViewLight";

export type Camera = { id: string, name: string, preset: CameraPreset, position: Vec3, target: Vec3, fov_deg: number, 
/**
 * The light this view was saved with: sun time, sky, exposure, lamps.
 * None: the view uses whatever light is live.
 */
light: ViewLight | null, };
