// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetCategory } from "./AssetCategory";

/**
 * An entry of the built-in object library.
 */
export type CatalogItem = { key: string, name: string, category: AssetCategory, width_mm: number, depth_mm: number, height_mm: number, elevation_mm: number, };
