// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirconSpec } from "./AirconSpec";
import type { AssetCategory } from "./AssetCategory";
import type { AssetLight } from "./AssetLight";
import type { DeviceKind } from "./DeviceKind";
import type { Mount } from "./Mount";

/**
 * An entry of the built-in object library.
 */
export type CatalogItem = { key: string, name: string, category: AssetCategory, width_mm: number, depth_mm: number, height_mm: number, elevation_mm: number, 
/**
 * Where the object mounts. Wall objects sit with their back (+y) on a
 * wall face; ceiling objects hang from the level height.
 */
mount: Mount, 
/**
 * The row it counts under in device schedules and the PH electrical
 * inspection form. None for furniture and fixtures that are not devices.
 */
device: DeviceKind | null, 
/**
 * Default light when placed. Only light fixtures have one.
 */
light: AssetLight | null, 
/**
 * Aircon units: line set and the manufacturer limits the review uses.
 */
aircon: AirconSpec | null, };
