// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * One chat message of a project.
 */
export type ChatMessage = { id: string, 
/**
 * The participant who sent it. Kept after they leave, so old messages
 * keep their name and color.
 */
author_id: string, author_name: string, color: number, text: string, 
/**
 * RFC 3339.
 */
sent_at: string, 
/**
 * Where the author's pointer was on the plan when they sent it from
 * cursor chat. None for messages from the chat panel.
 */
at: Point | null, level_id: string | null, 
/**
 * Sent by an AI client on the author's behalf (the MCP tool
 * `send_chat_message`). Shown with an AI tag.
 */
via_ai: boolean, };
