// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnShape } from "./ColumnShape";
import type { Point } from "./Point";

export type Column = { id: string, level_id: string, center: Point, shape: ColumnShape, 
/**
 * Diameter when round.
 */
width_mm: number, depth_mm: number, rotation_deg: number, material_id: string | null, };
