// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { Layer } from "./Layer";
import type { Level } from "./Level";
import type { Material } from "./Material";
import type { OpeningStyle } from "./OpeningStyle";
import type { OpeningType } from "./OpeningType";
import type { Point } from "./Point";
import type { ProjectSettings } from "./ProjectSettings";
import type { ReviewTarget } from "./ReviewTarget";
import type { Roof } from "./Roof";
import type { Side } from "./Side";
import type { WallAnchor } from "./WallAnchor";

export type Command = { "type": "add_wall", start: Point, end: Point, thickness_mm: number | null, height_mm: number | null, material_id: string | null, level_id: string | null, } | { "type": "add_wall_chain", points: Array<Point>, closed: boolean, thickness_mm: number | null, level_id: string | null, } | { "type": "add_rect_room", origin: Point, width_mm: number, depth_mm: number, name: string | null, thickness_mm: number | null, level_id: string | null, } | { "type": "set_wall_endpoints", wall_id: string, start: Point, end: Point, } | { "type": "set_wall_length", wall_id: string, length_mm: number, anchor: WallAnchor, } | { "type": "split_wall", wall_id: string, at_mm: number, } | { "type": "add_opening", wall_id: string, opening_type: OpeningType, offset_mm: number, width_mm: number | null, height_mm: number | null, sill_mm: number | null, style: OpeningStyle | null, 
/**
 * None means false. See `Opening::flip_side` for the convention.
 */
flip_side: boolean | null, flip_hinge: boolean | null, } | { "type": "resize_room", room_id: string, side: Side, delta_mm: number, } | { "type": "add_element", element: Element, } | { "type": "update_element", element: Element, } | { "type": "delete_elements", ids: Array<string>, } | { "type": "move_elements", ids: Array<string>, delta: Point, stretch_connected: boolean, } | { "type": "rotate_elements", ids: Array<string>, pivot: Point, angle_deg: number, } | { "type": "duplicate_elements", ids: Array<string>, delta: Point, } | { "type": "set_material", ids: Array<string>, material_id: string, } | { "type": "upsert_material", material: Material, } | { "type": "set_roof", roof: Roof, } | { "type": "set_project_settings", settings: ProjectSettings, } | { "type": "update_level", level: Level, } | { "type": "add_level", name: string | null, elevation_mm: number | null, height_mm: number | null, } | { "type": "delete_level", level_id: string, } | { "type": "set_layer", layer: Layer, } | { "type": "set_review_mark", target: ReviewTarget, note: string | null, } | { "type": "batch", label: string, commands: Array<Command>, };
