// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Footprint } from "./Footprint";
import type { Issue } from "./Issue";
import type { PipeNetwork } from "./PipeNetwork";
import type { ReviewMark } from "./ReviewMark";
import type { RoomGeometry } from "./RoomGeometry";
import type { ScheduleRow } from "./ScheduleRow";
import type { Totals } from "./Totals";
import type { WallGeometry } from "./WallGeometry";

export type Derived = { walls: Array<WallGeometry>, rooms: Array<RoomGeometry>, 
/**
 * Outer boundaries, used for roof and slab. One entry per closed building
 * on a level, largest first. A level with none has one entry with an
 * empty polygon. Consumers must handle several per level.
 */
footprints: Array<Footprint>, totals: Totals, 
/**
 * Design review items. Suggestions, never compliance statements.
 */
issues: Array<Issue>, 
/**
 * Pipe fittings, penetrations and quantities. Empty without pipes.
 */
pipes: PipeNetwork, 
/**
 * Object counts per level and room, for fixture tables and device
 * schedules. Only objects whose catalog item has a `device` kind or is a
 * sanitary, lighting, electrical, aircon or utility item, plus the
 * kitchen sink and the washing machine, which count as plumbing fixtures.
 */
schedule: Array<ScheduleRow>, 
/**
 * Review marks whose finding the checks no longer produce: resolved.
 */
review_resolved: Array<ReviewMark>, };
