// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Footprint } from "./Footprint";
import type { Issue } from "./Issue";
import type { PipeNetwork } from "./PipeNetwork";
import type { RoomGeometry } from "./RoomGeometry";
import type { Totals } from "./Totals";
import type { WallGeometry } from "./WallGeometry";

export type Derived = { walls: Array<WallGeometry>, rooms: Array<RoomGeometry>, 
/**
 * Outer boundaries, used for roof and slab. One entry per closed building
 * on a level, largest first. A level with none has one entry with an
 * empty polygon. Consumers must handle several per level.
 */
footprints: Array<Footprint>, totals: Totals, 
/**
 * Design review items. Suggestions, never compliance statements.
 */
issues: Array<Issue>, 
/**
 * Pipe fittings, penetrations and quantities. Empty without pipes.
 */
pipes: PipeNetwork, };
