// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Electrical and aircon device kinds, named after the rows of the PH
 * electrical inspection form so counts can be read straight into it.
 */
export type DeviceKind = "lighting_outlet" | "convenience_receptacle" | "special_purpose_outlet" | "switch" | "panelboard" | "smoke_detector" | "buzzer" | "push_button" | "aircon_indoor" | "aircon_outdoor" | "aircon_window";
