// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Diff = { added: Array<string>, modified: Array<string>, removed: Array<string>, 
/**
 * One plain sentence, for example "Moved 1 wall, stretched 2 walls".
 */
summary: string, };
