// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * Linear dimension between two plan points.
 */
export type Dimension = { id: string, level_id: string, a: Point, b: Point, 
/**
 * Signed distance of the dimension line from the a-b line.
 */
offset_mm: number, text_override: string | null, };
