// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Derived } from "./Derived";
import type { Project } from "./Project";

/**
 * Full document state. Sent to the frontend after every change. Projects are
 * small (hundreds of elements), so there is no partial sync.
 */
export type DocState = { project: Project, derived: Derived, 
/**
 * Increments on every apply, undo and redo.
 */
revision: number, can_undo: boolean, can_redo: boolean, undo_label: string | null, redo_label: string | null, };
