// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the optional ODA File Converter used for DWG.
 */
export type DwgConverterStatus = { configured: boolean, path: string | null, works: boolean, message: string, };
