// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Limits an AI edit to part of the plan (DECISIONS D30). The engine checks
 * every command the AI stages or commits against it (`guhit_core::scope`)
 * and refuses one that reaches outside, naming the element: the model reads
 * a tool error that starts with `out_of_scope:`. The copilot and MCP
 * clients are held to it alike.
 *
 * What the selection reaches is derived, never stored: a room reaches its
 * bounding walls, the doors and windows on its part of them, and what
 * stands inside it; a wall reaches its doors and windows; any other element
 * reaches itself. New elements must land inside the area of the selection
 * on its level. Project-wide changes (roof, levels, layers, settings) are
 * outside every scope. Changes the engine makes as a consequence (connected
 * walls stretching, dimensions following, links removed) are allowed.
 * docs/CONTRACT.md, "AI edit scope", has the full rules.
 */
export type EditScope = { 
/**
 * The selected elements. At least one.
 */
ids: Array<string>, };
