// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { Asset } from "./Asset";
import type { Camera } from "./Camera";
import type { Column } from "./Column";
import type { Dimension } from "./Dimension";
import type { Linework } from "./Linework";
import type { Opening } from "./Opening";
import type { ReferenceModel } from "./ReferenceModel";
import type { Room } from "./Room";
import type { Stair } from "./Stair";
import type { Underlay } from "./Underlay";
import type { Wall } from "./Wall";

export type Element = { "kind": "wall" } & Wall | { "kind": "opening" } & Opening | { "kind": "room" } & Room | { "kind": "column" } & Column | { "kind": "stair" } & Stair | { "kind": "asset" } & Asset | { "kind": "annotation" } & Annotation | { "kind": "dimension" } & Dimension | { "kind": "camera" } & Camera | { "kind": "underlay" } & Underlay | { "kind": "linework" } & Linework | { "kind": "reference_model" } & ReferenceModel;
