// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ElementKind = "wall" | "opening" | "room" | "column" | "stair" | "asset" | "annotation" | "dimension" | "camera" | "underlay" | "linework" | "reference_model" | "pipe";
