// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportResult = { 
/**
 * Absolute path of the written file.
 */
path: string, 
/**
 * Scale that was actually used, 1:N.
 */
scale_denominator: number | null, };
