// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

export type Footprint = { level_id: string, 
/**
 * Outer wall faces, counter-clockwise. Empty when no closed building.
 */
polygon: Array<Point>, area_mm2: number, };
