// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportLayer = { name: string, entity_count: number, 
/**
 * Walls the recognizer would produce from this layer at the suggested unit.
 */
detected_walls: number, 
/**
 * "#rrggbb" from the layer color, for the preview.
 */
color: string, };
