// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportMode } from "./ImportMode";
import type { Point } from "./Point";

export type ImportOptions = { mm_per_unit: number, 
/**
 * Layers to bring in. Empty means all.
 */
layers: Array<string>, mode: ImportMode, 
/**
 * Plan offset applied after scaling, so a drawing far from its origin lands near 0,0.
 */
offset: Point, level_id: string | null, };
