// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocState } from "./DocState";

export type ImportResult = { state: DocState, walls_added: number, linework_added: number, skipped: Array<string>, };
