// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportLayer } from "./ImportLayer";
import type { Point } from "./Point";

/**
 * What a DXF or DWG file contains, before the user decides how to import it.
 */
export type ImportInspection = { file_name: string, 
/**
 * Unit declared by the file ($INSUNITS), or None when it declares none.
 */
declared_unit: string | null, 
/**
 * mm per drawing unit the app suggests. The user must confirm it.
 */
suggested_mm_per_unit: number, layers: Array<ImportLayer>, 
/**
 * Bounding box in drawing units.
 */
min: Point, max: Point, };
