// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error shape for every IPC call.
 */
export type IpcError = { 
/**
 * Machine code: "not_found", "invalid", "no_document", "stale",
 * "io", "ai_not_configured", "ai_failed", "unknown_command", "bad_args".
 */
code: string, message: string, element_ids: Array<string>, };
