// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";
import type { Vec3 } from "./Vec3";

export type Issue = { 
/**
 * Stable for the same finding on the same elements.
 */
id: string, severity: Severity, 
/**
 * Machine code, for example "room_no_window", "door_narrow".
 */
code: string, message: string, element_ids: Array<string>, 
/**
 * Where the finding is, when it has one point (the pipe checks set it).
 * Plan x and y in mm, z above the floor of the first element's level.
 */
location: Vec3 | null, };
