// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type Issue = { 
/**
 * Stable for the same finding on the same elements.
 */
id: string, severity: Severity, 
/**
 * Machine code, for example "room_no_window", "door_narrow".
 */
code: string, message: string, element_ids: Array<string>, };
