// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a view's light fixtures are lit.
 */
export type LampMode = "auto" | "on" | "off";
