// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerKey = "walls" | "openings" | "rooms" | "columns" | "stairs" | "assets" | "annotations" | "dimensions" | "underlays" | "cold_water" | "hot_water" | "drainage" | "vent";
