// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerKey } from "./LayerKey";

export type Layer = { key: LayerKey, visible: boolean, locked: boolean, };
