// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Level = { id: string, name: string, elevation_mm: number, 
/**
 * Floor-to-floor height. Walls without their own height use this.
 */
height_mm: number, };
