// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * Imported vector linework (from DXF or DWG), kept as a tracing reference on
 * the Underlays layer. Not editable except move, rotate, delete. Coordinates
 * are already in project mm after the user confirmed the unit.
 */
export type Linework = { id: string, level_id: string, 
/**
 * Source file name and layer, for display: "site.dxf / A-WALL".
 */
name: string, 
/**
 * Polylines in plan mm. Closed ones repeat their first point at the end.
 */
polylines: Array<Array<Point>>, 
/**
 * "#rrggbb"
 */
color: string, locked: boolean, };
