// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LiveMode } from "./LiveMode";
import type { Participant } from "./Participant";

export type LiveStatus = { mode: LiveMode, 
/**
 * This computer's participant. None when off.
 */
self_id: string | null, 
/**
 * Everyone in the session, this computer included, host first.
 */
participants: Array<Participant>, 
/**
 * Host only: the invite to send to the people who should join. It holds
 * the host's addresses, a one-session secret and the pin of the host's
 * certificate. Anyone who has it can join while the session runs.
 */
invite: string | null, 
/**
 * Host only: where guests reach this computer, "192.168.1.20:1460".
 */
addresses: Array<string>, 
/**
 * The shared project.
 */
project_id: string | null, project_name: string | null, 
/**
 * Why the last session ended or why joining failed, in one sentence.
 * Cleared when a new session starts.
 */
notice: string | null, };
