// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A host's registration with the relay (DECISIONS D32, docs/RELAY.md), the
 * way guests outside its network or VPN reach it.
 */
export type LiveRelay = "off" | "connecting" | "ready" | "unavailable";
