// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Is this computer in a live session, and how.
 */
export type LiveMode = "off" | "hosting" | "joined" | "reconnecting";
