// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Procedural surface pattern hint for the 3D view and hatches.
 */
export type MaterialPattern = "none" | "chb" | "concrete" | "tile" | "wood_plank" | "roof_sheet" | "roof_tile" | "glass";
