// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialCategory } from "./MaterialCategory";
import type { MaterialPattern } from "./MaterialPattern";

export type Material = { id: string, name: string, category: MaterialCategory, 
/**
 * "#rrggbb"
 */
color: string, roughness: number, metalness: number, opacity: number, pattern: MaterialPattern, builtin: boolean, };
