// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An MCP client as it named itself in `clientInfo`.
 */
export type McpClientSeen = { name: string, version: string, 
/**
 * RFC 3339 UTC: its latest request.
 */
at: string, };
