// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpClientSeen } from "./McpClientSeen";

/**
 * The MCP server as the Connect agent dialog shows it (DECISIONS D35).
 */
export type McpStatus = { 
/**
 * The "Allow agents" switch. Off: every MCP request is refused.
 * Stored in settings.json as `mcp_enabled`, on by default.
 */
enabled: boolean, 
/**
 * True while the MCP listener is bound.
 */
listening: boolean, 
/**
 * The port it serves on, or tried to.
 */
port: number, 
/**
 * `http://127.0.0.1:{port}/mcp`.
 */
url: string, 
/**
 * Absolute path of the desktop executable, to run with `--mcp-stdio`.
 * None in the dev bridge.
 */
stdio_command: string | null, 
/**
 * The agent that used the server last, since the app started.
 */
last_client: McpClientSeen | null, 
/**
 * True when `mcp_claude_desktop_bundle` can write the extension file.
 */
claude_desktop_bundle: boolean, };
