// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whole-model exports produced by the backend.
 */
export type ModelFormat = "ifc" | "dxf3d" | "dwg";
