// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningStyle } from "./OpeningStyle";
import type { OpeningType } from "./OpeningType";

/**
 * A door or window hosted on a wall. It has no level of its own.
 */
export type Opening = { id: string, wall_id: string, opening_type: OpeningType, style: OpeningStyle, 
/**
 * Distance from the host wall start to the opening center, along the centerline.
 */
offset_mm: number, width_mm: number, height_mm: number, 
/**
 * Height of the sill above the level floor. 0 for doors.
 */
sill_mm: number, 
/**
 * Which side of the wall the leaf swings to. false: the left of the wall
 * direction start -> end (its counter-clockwise normal). true: the right.
 */
flip_side: boolean, 
/**
 * Which jamb carries the hinge. false: the jamb nearer the wall start.
 * true: the jamb nearer the wall end.
 */
flip_hinge: boolean, material_id: string | null, };
