// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who issued a command. Recorded in history and AI logs.
 */
export type Origin = "user" | "ai";
