// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParticipantRole } from "./ParticipantRole";

/**
 * A person in a live session.
 */
export type Participant = { id: string, name: string, 
/**
 * Index into the participant colors, `--peer-0` to `--peer-7`. The host
 * gives each participant a color no one else in the session has, while
 * colors last.
 */
color: number, role: ParticipantRole, };
