// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipeMaterial } from "./PipeMaterial";
import type { PipeSystem } from "./PipeSystem";

export type PipeTakeoffRow = { system: PipeSystem, material: PipeMaterial, diameter_mm: number, 
/**
 * Centerline length, rounded to the millimeter.
 */
length_m: number, run_count: number, };
