// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FittingKind } from "./FittingKind";
import type { Vec3 } from "./Vec3";

export type PipeFitting = { kind: FittingKind, 
/**
 * The run the fitting sits on. For a tee, the run that is joined.
 */
pipe_id: string, 
/**
 * For a tee, the run whose end joins. None for an elbow.
 */
branch_pipe_id: string | null, level_id: string, position: Vec3, 
/**
 * The larger diameter at the fitting.
 */
diameter_mm: number, 
/**
 * Elbow: the change of direction in degrees. Tee: the angle between the
 * branch and the run.
 */
angle_deg: number, };
