// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipeMaterial } from "./PipeMaterial";
import type { PipeSystem } from "./PipeSystem";
import type { Vec3 } from "./Vec3";

/**
 * A pipe run: straight segments through `points`, with a bend at every
 * interior point. Fittings, penetrations and quantities are derived
 * (`Derived::pipes`). Guhit places and coordinates pipes. It does not size
 * them: plumbing design is signed by a registered Master Plumber (RA 1378).
 */
export type Pipe = { id: string, level_id: string, system: PipeSystem, material: PipeMaterial, 
/**
 * Nominal size in mm, for example PPR 20 or uPVC 100. The 3D view draws
 * it as the outside diameter.
 */
diameter_mm: number, 
/**
 * Centerline points. x and y are plan mm. z is the height above the
 * level floor, negative below the slab. At least two points; two points
 * in a row are never equal. Drainage flows from the first to the last.
 */
points: Array<Vec3>, 
/**
 * Optional label, for example "Kitchen sink waste". May be empty.
 */
name: string, };
