// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PipeFitting } from "./PipeFitting";
import type { PipePenetration } from "./PipePenetration";
import type { PipeTakeoffRow } from "./PipeTakeoffRow";

/**
 * Everything derived from the pipes of a project. Positions use the pipe
 * convention: plan x and y, z above the floor of `level_id`.
 */
export type PipeNetwork = { fittings: Array<PipeFitting>, penetrations: Array<PipePenetration>, 
/**
 * One row per system, material and size. Sorted by system, then material,
 * then size.
 */
takeoff: Array<PipeTakeoffRow>, total_length_m: number, elbow_count: number, tee_count: number, 
/**
 * Penetrations: each needs a sleeve (slab, wall) or flashing (roof).
 */
sleeve_count: number, };
