// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The building service a pipe belongs to. Each system has its own layer.
 */
export type PipeSystem = "cold_water" | "hot_water" | "drainage" | "vent" | "storm" | "conduit" | "refrigerant" | "condensate";
