// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PenetrationKind } from "./PenetrationKind";
import type { Vec3 } from "./Vec3";

export type PipePenetration = { kind: PenetrationKind, pipe_id: string, 
/**
 * The wall crossed, for `Wall`. None otherwise.
 */
host_id: string | null, level_id: string, 
/**
 * Where the centerline crosses the middle of the slab, wall or roof.
 */
position: Vec3, 
/**
 * Unit direction of the pipe there, for drawing the sleeve.
 */
direction: Vec3, diameter_mm: number, };
