// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Orientation } from "./Orientation";
import type { PaperSize } from "./PaperSize";

export type PlanExportOptions = { level_id: string | null, paper: PaperSize, orientation: Orientation, 
/**
 * 1:N. None picks the largest common scale that fits the sheet.
 */
scale_denominator: number | null, show_dimensions: boolean, show_room_labels: boolean, show_assets: boolean, title_block: boolean, };
