// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Orientation } from "./Orientation";
import type { PaperSize } from "./PaperSize";
import type { SheetKind } from "./SheetKind";

export type PlanExportOptions = { level_id: string | null, paper: PaperSize, orientation: Orientation, 
/**
 * 1:N. None picks the largest common scale that fits the sheet.
 */
scale_denominator: number | null, show_dimensions: boolean, show_room_labels: boolean, show_assets: boolean, title_block: boolean, 
/**
 * Draw pipes on visible pipe layers, with a legend. DXF puts each system
 * on its own layer. Older callers that omit it get true.
 */
show_pipes: boolean, 
/**
 * Which sheet to make. Older callers that omit it get the plan.
 */
sheet: SheetKind, 
/**
 * Add a page listing open and set-aside review items with their notes
 * (PDF only). Wording stays "suggestion", never approval.
 */
review_page: boolean, };
