// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * Where a participant is and what they are doing. Sent many times a second,
 * never saved, never an undo step.
 */
export type Presence = { 
/**
 * Pointer on the plan in mm. None while the pointer is off the plan.
 */
cursor: Point | null, 
/**
 * The level they are looking at.
 */
level_id: string | null, 
/**
 * What they have selected.
 */
selection: Array<string>, 
/**
 * Cursor chat being typed, shown beside their pointer as they type.
 * None when cursor chat is closed. At most `MAX_CURSOR_CHAT_CHARS`.
 */
typing: string | null, 
/**
 * AI edits made from their computer may change only their selection
 * (DECISIONS D30): the copilot and MCP clients.
 */
ai_scope: boolean, };
