// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

/**
 * Someone's latest presence, as `presence_list` returns it.
 */
export type PresenceEntry = { participant_id: string, presence: Presence, };
