// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The name this computer shows to others: cursor label, chat, history.
 * Stored in `settings.json` (`profile_name`).
 */
export type Profile = { 
/**
 * Empty until the user picks one. Hosting and joining need a name.
 */
name: string, };
