// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectMeta = { id: string, name: string, created_at: string, updated_at: string, floor_area_m2: number, room_count: number, 
/**
 * PNG data URL, or None when no thumbnail was saved yet.
 */
thumbnail: string | null, };
