// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { Layer } from "./Layer";
import type { Level } from "./Level";
import type { Material } from "./Material";
import type { ProjectSettings } from "./ProjectSettings";
import type { Roof } from "./Roof";

export type Project = { schema_version: number, id: string, name: string, 
/**
 * RFC 3339 timestamps.
 */
created_at: string, updated_at: string, settings: ProjectSettings, levels: Array<Level>, layers: Array<Layer>, materials: Array<Material>, elements: Array<Element>, roof: Roof, };
