// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayUnit } from "./DisplayUnit";
import type { PaperSize } from "./PaperSize";

export type ProjectSettings = { 
/**
 * Display only. Stored values are always mm.
 */
display_unit: DisplayUnit, 
/**
 * Drawing scale 1:N, for example 100.
 */
scale_denominator: number, 
/**
 * Rotation of true north from +y, degrees counter-clockwise.
 */
north_angle_deg: number, paper: PaperSize, default_wall_thickness_mm: number, grid_mm: number, client_name: string, location: string, designer: string, };
