// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * An imported 3D model (glTF, GLB or OBJ) shown in the 3D view as context:
 * site, a neighbour, furniture, a massing from SketchUp. The file lives in
 * the project folder under `models/`; the backend serves its bytes.
 */
export type ReferenceModel = { id: string, level_id: string, name: string, file_name: string, 
/**
 * Plan position of the model origin.
 */
position: Point, rotation_deg: number, 
/**
 * Height of the model origin above the level floor.
 */
elevation_mm: number, 
/**
 * Multiply model units by this to get mm (a model in meters uses 1000).
 */
scale_to_mm: number, locked: boolean, };
