// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Render sizes, as the render panel offers them.
 */
export type RenderSize = "hd" | "qhd" | "4k" | "square";
