// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderKind } from "./RenderKind";
import type { TraceQuality } from "./TraceQuality";

/**
 * How a model view image was made, kept with its record so every computer
 * that opens the project can say so.
 */
export type RenderInfo = { kind: RenderKind, 
/**
 * Image size in pixels.
 */
width: number, height: number, 
/**
 * Samples per pixel of a path traced render, else 0.
 */
samples: number, 
/**
 * How long it took, seconds.
 */
seconds: number, quality: TraceQuality | null, 
/**
 * The graphics adapter it ran on, as the browser names it. Empty when
 * unknown.
 */
gpu: string, };
