// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a model view image was made.
 */
export type RenderKind = "capture" | "path_traced" | "enhanced" | "shadow_study";
