// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderStyle = { key: string, name: string, description: string, 
/**
 * Prompt fragment sent to the image provider.
 */
prompt: string, };
