// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Camera } from "./Camera";
import type { RenderSource } from "./RenderSource";

/**
 * A saved visual, always tied to the model revision and camera it came from.
 */
export type RenderRecord = { id: string, created_at: string, source: RenderSource, revision: number, camera: Camera, style_key: string | null, prompt: string, 
/**
 * Absolute path of the PNG inside the project folder.
 */
image_path: string, };
