// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderQuality } from "./RenderQuality";

export type RenderAiRequest = { 
/**
 * The Tier 1 capture (source ModelView) to condition on.
 */
source_render_id: string, style_key: string | null, 
/**
 * Free text: building type, materials, mood, time of day.
 */
prompt: string, quality: RenderQuality, 
/**
 * True keeps geometry, camera and composition strictly (the default).
 */
keep_geometry: boolean, };
