// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Camera } from "./Camera";
import type { RenderInfo } from "./RenderInfo";
import type { RenderSource } from "./RenderSource";

/**
 * A saved visual, always tied to the model revision and camera it came from.
 */
export type RenderRecord = { id: string, created_at: string, source: RenderSource, revision: number, camera: Camera, style_key: string | null, prompt: string, 
/**
 * Absolute path of the PNG inside the project folder.
 */
image_path: string, 
/**
 * For an AI visualization: the model-view capture it was made from, so
 * the UI can show the two side by side.
 */
source_render_id: string | null, 
/**
 * For an AI visualization: provider and model, for example "gemini/gemini-3.1-flash-image".
 */
provider: string | null, 
/**
 * For a model view: how it was made. None for older records and AI
 * visualizations.
 */
info: RenderInfo | null, };
