// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderRecord } from "./RenderRecord";

export type RenderAiResult = { record: RenderRecord, 
/**
 * Seconds the provider took.
 */
seconds: number, };
