// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which hosted image model renders visualizations. Keys never reach the frontend.
 */
export type RenderAiSettings = { 
/**
 * "gemini" for now; the abstraction allows others later.
 */
provider: string, has_api_key: boolean, model: string, 
/**
 * Plain wording of the cost per image at the current model, for the UI.
 */
cost_hint: string, };
