// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewTarget } from "./ReviewTarget";

/**
 * A review item the designer set aside. Only "ignored" is stored.
 */
export type ReviewMark = { target: ReviewTarget, 
/**
 * Why it is set aside. The UI asks for one.
 */
note: string, };
