// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewTarget = { "kind": "issue", id: string, } | { "kind": "check", code: string, } | { "kind": "element", code: string, element_id: string, };
