// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { RoofKind } from "./RoofKind";

/**
 * One roof preset over the building footprint (`Derived::footprint`).
 */
export type Roof = { kind: RoofKind, pitch_deg: number, overhang_mm: number, thickness_mm: number, 
/**
 * Ridge direction for gable, slope direction for shed.
 */
ridge_axis: Axis, material_id: string | null, };
