// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomUsage = "living" | "dining" | "kitchen" | "bedroom" | "master_bedroom" | "bathroom" | "powder_room" | "laundry" | "garage" | "porch" | "hallway" | "storage" | "office" | "other";
