// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";
import type { RoomUsage } from "./RoomUsage";

/**
 * A named space. Its polygon is derived: it is the closed wall face that
 * contains `seed`. See `Derived::rooms`.
 */
export type Room = { id: string, level_id: string, name: string, usage: RoomUsage, seed: Point, floor_material_id: string | null, 
/**
 * True while the name was assigned by auto-detection and never edited.
 */
auto_named: boolean, };
