// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

export type RoomGeometry = { room_id: string, 
/**
 * Net interior polygon on the inner wall faces, counter-clockwise.
 */
polygon: Array<Point>, 
/**
 * Same face on wall centerlines.
 */
centerline_polygon: Array<Point>, 
/**
 * Net interior area.
 */
area_mm2: number, perimeter_mm: number, 
/**
 * Good label position, guaranteed inside the polygon.
 */
label_point: Point, wall_ids: Array<string>, };
