// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKind } from "./DeviceKind";
import type { ScheduleGroup } from "./ScheduleGroup";

/**
 * How many of one catalog item stand in one room of one level.
 */
export type ScheduleRow = { level_id: string, 
/**
 * The room the objects stand in. None when outside every room.
 */
room_id: string | null, group: ScheduleGroup, catalog_key: string, 
/**
 * From the catalog item, when it is a device.
 */
device: DeviceKind | null, count: number, };
