// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The plan sheets a PH permit and hand-off set asks for. Every sheet keeps
 * the title block; the signing professional's fields stay blank.
 */
export type SheetKind = "plan" | "lighting" | "power" | "plumbing" | "plumbing_isometric" | "aircon";
