// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plan side of a room, by the outward normal of its bounding wall(s).
 */
export type Side = "north" | "south" | "east" | "west";
