// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geographic site of the project, used only for the sun position.
 */
export type Site = { 
/**
 * City preset key ("manila", "cebu", ...) or "custom". Display only.
 */
city: string, 
/**
 * Degrees, north positive.
 */
latitude_deg: number, 
/**
 * Degrees, east positive.
 */
longitude_deg: number, 
/**
 * Minutes east of UTC. Philippine time is 480, with no daylight saving.
 */
utc_offset_min: number, };
