// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnapshotMeta = { id: string, label: string, created_at: string, revision: number, 
/**
 * True for automatic snapshots, false for user-named versions.
 */
auto: boolean, };
