// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * Straight single-flight stair. `origin` is the center of the first riser,
 * the flight runs along the rotated +y direction. Going depth is
 * `run_mm / riser_count`; total rise is the level height.
 */
export type Stair = { id: string, level_id: string, origin: Point, rotation_deg: number, width_mm: number, run_mm: number, riser_count: number, };
