// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Totals = { 
/**
 * Sum of net room areas.
 */
floor_area_m2: number, 
/**
 * Sum of footprint areas.
 */
gross_area_m2: number, wall_length_m: number, room_count: number, door_count: number, window_count: number, };
