// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The path tracer's time and sample budget: Quick aims at a minute at HD,
 * Final at five.
 */
export type TraceQuality = "quick" | "final";
