// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * Imported raster plan used as a tracing reference. The image file lives in
 * the project folder; the backend serves its bytes.
 */
export type Underlay = { id: string, level_id: string, file_name: string, 
/**
 * Plan position of the image's bottom-left corner.
 */
position: Point, width_px: number, height_px: number, 
/**
 * Scale. Must be confirmed by the user, never assumed.
 */
mm_per_px: number, scale_confirmed: boolean, rotation_deg: number, opacity: number, locked: boolean, };
