// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * World-space point in mm: x east, y north, z up.
 */
export type Vec3 = { x: number, y: number, z: number, };
