// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LampMode } from "./LampMode";
import type { SkyKind } from "./SkyKind";

/**
 * Sun, sky and exposure saved with a view (SketchUp saves shadow time per
 * scene; Enscape only the sun angle). Local time at `ProjectSettings::site`.
 */
export type ViewLight = { 
/**
 * 1 to 12.
 */
month: number, 
/**
 * 1 to 31.
 */
day: number, 
/**
 * Minutes after local midnight, 0 to 1439.
 */
minutes: number, sky: SkyKind, 
/**
 * Locked exposure in EV relative to the auto value. None: auto.
 */
exposure_ev: number | null, 
/**
 * Whether the fixtures are lit.
 */
lamps: LampMode, };
