// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

/**
 * A straight wall defined by its centerline.
 */
export type Wall = { id: string, level_id: string, start: Point, end: Point, thickness_mm: number, 
/**
 * None means use the level height.
 */
height_mm: number | null, material_id: string | null, };
