// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from "./Point";

export type WallGeometry = { wall_id: string, length_mm: number, 
/**
 * Plan outline with joins resolved (mitred corners), counter-clockwise.
 */
outline: Array<Point>, 
/**
 * True when one face of the wall is on the outside of the footprint.
 */
exterior: boolean, 
/**
 * Walls sharing the start and end joints.
 */
joined_at_start: Array<string>, joined_at_end: Array<string>, };
