// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the window answers to a `WindowRequest`.
 */
export type WindowReply = { 
/**
 * Records saved to Visuals (render, capture_view), in order.
 */
render_ids: Array<string>, 
/**
 * PNG or JPEG data URL: the plan (capture_plan), or a preview of the
 * first saved image at most 1568 px on its long side.
 */
image: string | null, 
/**
 * One sentence for the caller: how the render went, what was saved, or
 * why it is an enhanced capture instead of a path traced render.
 */
note: string, };
