// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowTask } from "./WindowTask";

/**
 * A task for the window, because the 3D renderer and the plan canvas live
 * there (DECISIONS D31). MCP render and capture tools use it.
 */
export type WindowRequest = { id: string, task: WindowTask, };
