// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderSize } from "./RenderSize";
import type { TraceQuality } from "./TraceQuality";

export type WindowTask = { "type": "render", views: Array<string>, quality: TraceQuality, size: RenderSize, } | { "type": "capture_view", camera_id: string | null, } | { "type": "capture_plan", level_id: string | null, };
